### ISSUE TITLE
Generierung des Skriptes

### ISSUE THREAD

**Issue by SebastianZug** [SebastianZug/VL_Softwareentwicklung#16]
Sammlung von Ideen für die Verbesserung der GitHub-Actions rund um die Generierung des Skripts ausgehend von den Kursmaterialien:

- Zeilenumbrüche im langen Einzeiler mit den Pandoc Parametern. Hier wäre eine mehrzeilige Darstellung wünschenswert
- Einführung eines Titelblattes (das unter anderem alle beitragenden Autoren, das aktuelle Datum und eine Versionsnummer nennt)
- Verbesserung der Codeausgaben im pdf ... dabei ist besteht das Problem, dass quasi zwei Welten abgedeckt werden müssen - die ASCII Skizzen und Codesnippets.
- Realisierung der fehlenden Symbole für das Box-Drawing 
- Verbesserte Darstellung der Quizze

**Comment by andre-dietrich** [comment]
Darstellung von Fußnoten? Bilder entsprechen der Seitengröße skalieren... Makros entfernen oder auflösen.
