### ISSUE TITLE
Statische Code Analyse

### ISSUE THREAD

**Issue by SebastianZug** [SebastianZug/VL_Softwareentwicklung#48]
Welche Tools nutzen Sie in Ihren Entwicklungsumgebungen, um Ihre Codestruktur zu verbessern? Reagieren Sie auf jede Linter Nachricht oder ignorieren Sie diese geflissen?

**Comment by KoKoKotlin** [comment]
Also ich benutze IntelliJ Rider als IDE und in diese ist bereits ein Linter integriert, den man auch konfigurieren kann, wenn man mit der Standartkonfiguration nicht zufrieden ist.
Ich nehme Lintingerrors in Projekten, die ich nur für mich selbst schreibe und die sehr kurz sind und vor allem in Programmiersprachen, mit denen ich schon sehr vertraut bin meistens nicht ernst bzw. schalte den Linter aus. 
Wenn ich an größeren Projekten arbeite bzw. eine neue Programmiersprache lerne oder an Projekten an denen mehrere beteiligt sind arbeite, dann beachte und korrigiere ich die Fehler, die der Linter anzeigt.
